"""add extracted text and file details to documents

Revision ID: 876c9c3a994f
Revises: 3aa3670b7b73
Create Date: 2026-09-19 12:03:50.555498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876c9c3a994f'
down_revision: Union[str, Sequence[str], None] = '3aa3670b7b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.String(length=20), server_default='uploaded', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'size_bytes')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
